"""Signal dataclass for trading signals."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by a strategy."""

    signal_id: str
    strategy_name: str
    symbol: str
    action: Literal["BUY", "SELL", "HOLD"]
    confidence: float
    reason: str
    suggested_quantity: int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")

        if self.action not in ("BUY", "SELL", "HOLD"):
            raise ValueError(f"Invalid action: {self.action}")

    @property
    def is_actionable(self) -> bool:
        """Check if signal requires action (not HOLD)."""
        return self.action != "HOLD"

    @property
    def is_buy(self) -> bool:
        """Check if this is a buy signal."""
        return self.action == "BUY"

    @property
    def is_sell(self) -> bool:
        """Check if this is a sell signal."""
        return self.action == "SELL"
